language: r
cache: packages

sudo: disabled

# cache local R libraries directory:
cache: packages

## I don't understand why the r_packages section below doesn't work...
install: 
  - Rscript -e "install.packages(\"lintr\", repos = \"http://cran.rstudio.com\")"

r_packages:
  - lintr

# Lint
script:
  - ./travis-linter.sh
